server.port: 8000
spring:
  profiles.active: dev
  application.name: s2u2m-demo
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.time_zone: UTC
  jackson.time-zone: UTC
logging:
  # 日志配置由 logback-spring.xml 处理，支持 traceId 追踪
s2u2m:
  security:
    jwt:
      publicKey: classpath:jwt-rsa-key.pub
      privateKey: classpath:jwt-rsa-key.pem
