server.port: 8080
spring:
  profiles.active: dev
  application.name: s2u2m-demo
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.time_zone: UTC
    show-sql: true
  jackson.time-zone: UTC
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: info
    com.s2u2m.services: info
s2u2m:
  security:
    jwt:
      publicKey: classpath:jwt-rsa-key.pub
